{
 "title": "Earthquake Tracker",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Live Global Earthquakes Activiry",
   "type": "geomap",
   "description": "Shows the most recent earthquakes recorded.",
   "gridPos": { "h": 18, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  place AS \"Location\",\r\n  to_timestamp(time_ms/1000.0) AS \"Time\",\r\n  magnitude AS \"Magnitude\",\r\n  depth AS \"Depth\",\r\n  latitude AS \"Latitude\",\r\n  longitude AS \"Longitude\"\r\nFROM earthquakes\r\nORDER BY time_ms DESC\r\nLIMIT 50;\r\n"
    }
   ]
  },
  {
   "title": "Earthquake Record",
   "type": "table",
   "description": "List of latest recorde earthquakes.",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  to_timestamp(time_ms/1000.0) AS \"Time\",\r\n  place AS \"Location\",\r\n  magnitude AS \"Magnitude\"\r\nFROM earthquakes\r\nORDER BY time_ms DESC\r\nLIMIT 100;\r\n"
    }
   ]
  },
  {
   "title": "Time Series",
   "type": "timeseries",
   "description": "Shows earthquake activite over a period of time.",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  to_timestamp(\r\n    floor(extract(epoch FROM to_timestamp(time_ms/1000.0)) / 1800) * 1800\r\n  ) AS time,\r\n  COUNT(*) AS earthquakes\r\nFROM earthquakes\r\nWHERE to_timestamp(time_ms/1000.0)\r\n      BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  }
 ]
}